// <auto-generated />
namespace cspWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AvailableFieldinOfferingModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AvailableFieldinOfferingModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201708041821082_Available Field in Offering Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
